apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-5bjf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-5bjf
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-5bjf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-5bjf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-5bjf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sgam-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-5bjf@sha256:ad35b8ba164595fbb985a0c148624fa08ca184ca9fe6290235e5047ded303c94
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
